### ISSUE TITLE
OOps

### ISSUE THREAD

**Issue by pedromorgan** [ekini/go-milter#1]
So is this project active and used ?

Maybe not, and alike some of mine..
..  and cleaning out the house
https://www.youtube.com/watch?v=_C66ppsGmiY

Am deleting projects which not fork moving forward.. inc my fork..
Is that ok..
less noise ;-)
love u

and here is charlie, a fiend of mine singing a song for u,..
claening house..
https://www.youtube.com/watch?v=-CfYQWkaOBg

Ta ;-))

**Comment by ekini** [comment]
Hi Pete!
It's not used by me, but might be useful to someone else?
